### ISSUE TITLE
Merge repo into eclipse.platform.ui

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui.tools#31]
I suggest to merge this one into eclipse.platform.ui. Any objections? cc @laeubi and @akurtakov

**Comment by akurtakov** [comment]
Every single simplification matters and there are way too many obstacles for many to land so if you can do this one - go for it.

**Comment by laeubi** [comment]
Sounds reasonable.

**Comment by vogella** [comment]
Maybe better target directly eclipse.platform repo? This seems our all-in-one final target anyway. IMHO the best (releng) option is to end up with one repo.

**Comment by akurtakov** [comment]
IMHO put it in UI so the two merges can go simultaneosly now :) . We are far from targetting one repo  yet so let's aim for best shortterm gain.

**Comment by laeubi** [comment]
Last time it was said that we should aim for

- platform
- platform.ui

as a first step because of build times and separation.

**Comment by akurtakov** [comment]
> Last time it was said that we should aim for
> 
>     * platform
> 
>     * platform.ui
> 
> 
> as a first step because of build times and separation.

I stand behind this 100 % for now.

**Comment by vogella** [comment]
So the merged repo goes into a "tools" subdirectory in platform.ui as we do for merges in platform?

**Comment by akurtakov** [comment]
> 

Sounds good to me.

**Comment by merks** [comment]
I'm not sure all these things are tools?  The source repo was "ua" for user assistance.  It seems to me all these things are mostly framework components, not tools...

**Comment by laeubi** [comment]
@merks I think if we found that the previous categories are wrong, we can easily move the items around to a more suitable place after the merge.

Alternative would be to help @vogella to move them to a proper place as part of the merge (but I can't decide on that as I don't know that in detail)

**Comment by akurtakov** [comment]
Someone named them tools (even bundle names are o.e.e4.tools.\*) so even if being general components tools is still good place in the sense of folder with o.e.e4.tools.* components. 
If the question is about renaming the bundles and etc. that's far bigger discussion which shouldn't interfere with merging repos.

**Comment by merks** [comment]
I don't have a really strong opinion but at some point "ua" seemed like good name (to some human beings) for some group of things, and perhaps folks looking for things in that group might not be helped by looking in tools.   We are talking about these, right?

![image](https://user-images.githubusercontent.com/208716/218696966-98bb2f16-5cee-4144-8d17-78cd0d37bc11.png)

No sign of tools here.  Just saying. 😉

**Comment by vogella** [comment]
@merks you commenting on the wrong issue, this is the merge from ui.tools not https://github.com/eclipse-platform/eclipse.platform/issues/324 which you are referring too.

**Comment by merks** [comment]
Sorry !!!  Now it all makes perfect sense. Sorry sorry.

**Comment by akurtakov** [comment]
Happens to me quite often *thanks to* multitasking :)

**Comment by vogella** [comment]
Lets see what CI error we get this time https://github.com/eclipse-platform/eclipse.platform.ui/pull/602

**Comment by vogella** [comment]
Done

**Comment by vogella** [comment]
FYI, AFAICS history for the merged files is still available.

![image](https://user-images.githubusercontent.com/139910/220086383-ce6a5fd8-2890-4a7b-b224-a5f429396725.png)

**Comment by vogella** [comment]
For existing files from platform.ui 

![image](https://user-images.githubusercontent.com/139910/220087101-fcf6133c-e357-4348-86b6-2e55162463e8.png)

**Comment by merks** [comment]
Why were maven natures and filters added to the .project files?

![image](https://user-images.githubusercontent.com/208716/220089760-b1f04d62-6768-45ac-bfca-b493d7a55e4e.png)

Also, why do we need .polyglot.META-INF?

**Comment by vogella** [comment]
@merks the maven natures were added automatically by the pde-m2e tooling. Fighting such automation is time consuming. cc @laeubi 

I will remove the .poly... stuff and add the file to the .gitignore.

**Comment by vogella** [comment]
@merks where do you see .polyglot.META-INF? find . -name ".polyglot.META-INF" does not find anything on my machine.

**Comment by merks** [comment]
Probably/maybe m2e is generating them?

**Comment by akurtakov** [comment]
These are runtime artifacts of tycho when using pomless builds and they are deleted at end of build. As visible from the screenshots they are ignored by git.

**Comment by merks** [comment]
I've never done a Tycho build so I don't know where they came from.  An even bigger problem is that all the .project files are missing for the tools projects:

![image](https://user-images.githubusercontent.com/208716/220095035-4e85a00f-dd94-4509-b0ee-495f58ad710b.png)

**Comment by vogella** [comment]
@merks Thanks for noticing. Fixed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/605

**Comment by laeubi** [comment]
When the maven nature is enabled, the files are created as part of the project import, so I think the issue is more that the .project files are missing, then they are handled as maven projects and then you get the maven nature and the temp files (of course you can ignore them).

I once suggested that git ignored files can be automatically filtered from the view, but I think this was never considered further.

**Comment by merks** [comment]
Now I see problems with "dirty" state after these import successfully.

![image](https://user-images.githubusercontent.com/208716/220098782-e62d9882-249f-4bf9-8e15-a33f0410a53b.png)

**Comment by merks** [comment]
I guess it's best to add a /*/*/*/bin/ to the root .gitignore?

**Comment by iloveeclipse** [comment]
`/**/bin/`, see https://github.com/eclipse-platform/eclipse.platform.ui/pull/606

**Comment by iloveeclipse** [comment]
The SDK build fails with
```
12:46:26  [ERROR] Cannot resolve project dependencies:
12:46:26  [ERROR]   Software being installed: org.eclipse.jdt 3.19.0.qualifier
12:46:26  [ERROR]   Missing requirement: org.eclipse.e4.ui.model.workbench 2.3.0.qualifier requires 'osgi.bundle; org.eclipse.e4.emf.xpath 0.1.100' but it could not be found
12:46:26  [ERROR]   Cannot satisfy dependency: org.eclipse.e4.ui.workbench 1.14.100.qualifier depends on: osgi.bundle; org.eclipse.e4.ui.model.workbench 1.2.0
12:46:26  [ERROR]   Cannot satisfy dependency: org.eclipse.jdt 3.19.0.qualifier depends on: osgi.bundle; org.eclipse.ui.intro [3.2.0,4.0.0)
12:46:26  [ERROR]   Cannot satisfy dependency: org.eclipse.ui.intro 3.6.600.qualifier depends on: osgi.bundle; org.eclipse.e4.ui.workbench 0.0.0
12:46:26  [ERROR] 
12:46:26  [ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
12:46:26  [ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.jdt:org.eclipse.jdt:3.19.0-SNAPSHOT @ /home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.jdt/org.eclipse.jdt/pom.xml: See log for details -> [Help 1]
12:46:26  [ERROR] 
12:46:26  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
12:46:26  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
12:46:26  [ERROR] 
12:46:26  [ERROR] For more information about the errors and possible solutions, please read the following articles:
12:46:26  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

Looks like tools has a dependency to JDT? So how that build was working before?

**Comment by vogella** [comment]
org.eclipse.e4.tools.jdt.templates has a dependency to JDT since a long time. Not sure how the build process did handle that so far.

**Comment by iloveeclipse** [comment]
> Not sure how the build process did handle that so far.

I assumed we tried to build SDK before merging?

**Comment by merks** [comment]
Another fun small problem.  There are two readme files that are case-insensitively the same. 

https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/README.MD
https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/README.md

So on Windows, one will always show as deleted because only one can exist in the Stupid windows file system.

![image](https://user-images.githubusercontent.com/208716/220103954-333f5b9f-8fcd-4280-aa58-ecddc0db1dca.png)

Please decide which one to delete....

**Comment by iloveeclipse** [comment]
In case no one has idea how to deal with JDT dependency, simplest solution would be to disable building org.eclipse.e4.tools.jdt.templates & remove if from org.eclipse.e4.core.tools.feature.

**Comment by vogella** [comment]
> In case no one has idea how to deal with JDT dependency, simplest solution would be to disable building org.eclipse.e4.tools.jdt.templates & remove if from org.eclipse.e4.core.tools.feature.

Yeah, I'm doing this right now....

**Comment by iloveeclipse** [comment]
> Please decide which one to delete....

README.md is the "better one", so README.MD is to be deleted.

**Comment by vogella** [comment]
> > In case no one has idea how to deal with JDT dependency, simplest solution would be to disable building org.eclipse.e4.tools.jdt.templates & remove if from org.eclipse.e4.core.tools.feature.
> 
> Yeah, I'm doing this right now....

https://github.com/eclipse-platform/eclipse.platform.ui/pull/608

**Comment by akurtakov** [comment]
So if one does just `mvn clean verify` (muscle memory) build works, one has to explictly pass -DaggregatorBuild=true to see the issue. This explains why issue was not catched.

**Comment by vogella** [comment]
> So if one does just `mvn clean verify` (muscle memory) build works, one has to explictly pass -DaggregatorBuild=true to see the issue. This explains why issue was not catched.

I also do not see a GH code verification action for PR in the aggregator repo https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/.github/workflows

**Comment by laeubi** [comment]
I'll try to take a look at the build issue as soon as I'm finished with some tasks, but probably one want to enable that option for that repo?

**Comment by vogella** [comment]
JDT templates removed from the build and re-triggered I-build https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/140/

**Comment by iloveeclipse** [comment]
> JDT templates removed from the build and re-triggered I-build

@vogella: If that "JDT templates" thing is supposed to be useful for e4, please create an issue to enable them again.

**Comment by iloveeclipse** [comment]
Now we face xpath issue again:
```
14:29:39  [ERROR]   Missing requirement: org.eclipse.e4.ui.model.workbench 2.3.0.qualifier requires 'osgi.bundle; org.eclipse.e4.emf.xpath 0.1.100' but it could not be found
```

**Comment by merks** [comment]
I think that project got deleted maybe?

I'm having trouble finding it and dependencies on it in my workspace resolve to the binary plugins in the target platform not to a workspace project.

![image](https://user-images.githubusercontent.com/208716/220123273-96c26c2a-79cd-4716-9d29-0e2104faddc6.png)

**Comment by iloveeclipse** [comment]
> I think that project got deleted maybe?

That happened at very beginning with 708cf228e289b3dd96416ccc6b153c9606cec620
@vogella : why?

**Comment by akurtakov** [comment]
No jxpath no CVEs :).

**Comment by vogella** [comment]
> No jxpath no CVEs :).

I restorted it with https://github.com/eclipse-platform/eclipse.platform.ui/pull/610, this was unintentially deleted and as the features live in another repo then the plug-ins I did not notice.

**Comment by akurtakov** [comment]
Now seriously, this shows how big of an issue our many repositories with many cyclic references repositories is if such an issue happens and the subrepo build tells us all is fine.

**Comment by akurtakov** [comment]
> I restorted it with [eclipse-platform/eclipse.platform.ui#610](https://github.com/eclipse-platform/eclipse.platform.ui/pull/610), this was unintentially deleted and as the features live in another repo then the plug-ins I did not notice.

I think you should revert the jdt.templates change too.

**Comment by vogella** [comment]
> > I restorted it with [eclipse-platform/eclipse.platform.ui#610](https://github.com/eclipse-platform/eclipse.platform.ui/pull/610), this was unintentially deleted and as the features live in another repo then the plug-ins I did not notice.
> 
> I think you should revert the jdt.templates change too.

Lets do this after the other issue is solved.

**Comment by merks** [comment]
Odd that the test dependency on it didn't fail the build...

![image](https://user-images.githubusercontent.com/208716/220127527-1b51374f-d299-4302-98d4-36ebe889942c.png)

**Comment by akurtakov** [comment]
It was satisfied just fine from I-builds repo where the bundle exists so no reason for the test bundle to not resolve.

**Comment by merks** [comment]
@akurtakov Ah, now it all make sense!  Thanks.

**Comment by vogella** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/610 merged, next try. Unfortunately I be away from the laptop soon, so if any work is still requred I can look at it tomorrow.

**Comment by vogella** [comment]
Would be more effective if the source bundle creation could be after the real compilation.

![image](https://user-images.githubusercontent.com/139910/220134849-79eed542-de29-4b15-b569-6eb9952e606b.png)

**Comment by akurtakov** [comment]
After the build repos are not clean so either it would have to be cleaned or even worse repos would have to be cloned again. This raise the question who needs the source tarball anymore? It was added by Red Hat and used for the Fedora/RHEL rpm builds which we no longer use so maybe no one uses them at all.

**Comment by vogella** [comment]
@akurtakov I created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/882 to retire the source tarball generation.

**Comment by vogella** [comment]
Build successful and AFAICS no new test errors ( https://download.eclipse.org/eclipse/downloads/drops4/I20230219-1800/testResults.php) , so lets close this. Please open new issues in in eclipse.platform.ui if you find another issue. 

Thanks for the help to the involved people.

**Comment by akurtakov** [comment]
Would you please revert the jdt.templates removal from feature?

**Comment by vogella** [comment]
> Would you please revert the jdt.templates removal from feature?

https://github.com/eclipse-platform/eclipse.platform.ui/pull/612
